---
- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/

- name: Create the WordPress directory 
  file:
    path: /srv/wordpress/    
    state: directory
    owner: wordpress
    group: wordpress
    mode: 0775

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  unarchive:
    creates: /srv/wordpress
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/wordpress


#- name: Fetch random salts for WordPress config
#  get_url:
#    url: https://api.wordpress.org/secret-key/1.1/salt/
#    dest: /tmp/salt.php

#  register: "wp_salt"
#  become: no
#  become_method: sudo
#  changed_when: true
#  delegate_to: localhost

# this is the required pip package
- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL
  pip:
    name: pymysql
    state: present

#- name: Create WordPress database
#  mysql_db: name={{ wp_db_name }} state=present login_user={{ wp_db_user }} login_password={{ wp_db_password }}

- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t

#- name: Start php-fpm Service
#  service: name=php-fpm state=started enabled=yes
